version: '3.5'
services:
  web:     
    image: matrixx333/novifrontend 
    build: 
      context: client
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - webapi   
    ports:
        - "80:80" 
    networks:
      - backend
  webapi:    
    image: matrixx333/novibackend
    build: 
      context: Api
      dockerfile: Dockerfile
    container_name: webapi
    ports:
        - "5000:5000"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"